/**
 * server/routes/checkin.js
 *
 * Three REST endpoints for the Mode Mentor check-in pipeline:
 *
 *  POST /api/checkin/text   — text only
 *  POST /api/checkin/photo  — image only (multipart)
 *  POST /api/checkin        — text + optional image (multipart, full fusion)
 *
 * Every response includes `disclaimer` per spec.
 * Raw text and image buffers are never logged (enforced by middleware).
 */

'use strict';

const express = require('express');
const multer  = require('multer');

const textClassifier  = require('../services/textClassifier');
const facialClassifier = require('../services/facialClassifier');
const geminiService = require('../services/geminiService');
const { Checkin, EmotionResult, User } = require('../models');
const { awardPoints } = require('../services/gamification');
const { generateRecommendation } = require('../services/recommendationEngine');
const { requireAuth } = require('../middleware/authMiddleware');
const DISCLAIMER = 'This analysis was generated by AI and is not a medical diagnosis.';

const router = express.Router();

const MAX_UPLOAD_MB = parseInt(process.env.MAX_UPLOAD_MB || '5', 10);

// Multer: store upload in memory buffer, never to disk
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: MAX_UPLOAD_MB * 1024 * 1024 },
  fileFilter(req, file, cb) {
    if (/image\/(jpeg|jpg|png|webp)/.test(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error('Only JPEG, PNG, or WebP images are accepted.'));
    }
  },
});

// ── Validation helpers ──────────────────────────────────────────────────────

function requireEmployeeId(req, res, next) {
  const id = req.body?.employeeId || req.body?.get?.('employeeId');
  if (!id || typeof id !== 'string' || !id.trim()) {
    return res.status(400).json({ error: 'employeeId is required.', disclaimer: DISCLAIMER });
  }
  next();
}

function requireText(req, res, next) {
  const text = req.body?.text;
  if (!text || typeof text !== 'string' || !text.trim()) {
    return res.status(400).json({ error: 'text field is required.', disclaimer: DISCLAIMER });
  }
  next();
}

// ── POST /api/checkin/text ──────────────────────────────────────────────────
// Body: { employeeId: string, text: string }

router.post('/text', requireAuth, requireEmployeeId, requireText, async (req, res, next) => {
  try {
    const { text } = req.body;
    const textResult = await textClassifier.classify(text);

    res.json({
      ...textResult,
      disclaimer: DISCLAIMER,
    });
  } catch (err) {
    next(err);
  }
});

// ── POST /api/checkin/photo ─────────────────────────────────────────────────
// Multipart: employeeId (field) + image (file)

router.post('/photo', requireAuth, upload.single('image'), requireEmployeeId, async (req, res, next) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'An image file is required.', disclaimer: DISCLAIMER });
    }

    if (!facialClassifier.isReady()) {
      return res.status(503).json({
        error: 'Facial analysis is not available on this server (text-only mode).',
        disclaimer: DISCLAIMER,
      });
    }

    // Process in-memory buffer — never written to disk
    const faceResult = await facialClassifier.classify(req.file.buffer);

    if (!faceResult) {
      return res.status(422).json({
        error: 'No face detected in the uploaded image. Please upload a clear selfie.',
        disclaimer: DISCLAIMER,
      });
    }

    res.json({
      ...faceResult,
      disclaimer: DISCLAIMER,
    });
  } catch (err) {
    next(err);
  }
});

// ── POST /api/checkin ───────────────────────────────────────────────────────
// Multipart: employeeId, text? (field), image? (file)
// Runs fusion. At least one of text or image must be provided.

router.post('/', requireAuth, upload.single('image'), requireEmployeeId, async (req, res, next) => {
  try {
    const text        = req.body?.text?.trim() || null;
    const quickMood   = req.body?.quickMood?.trim() || req.body?.quick_mood?.trim() || null;
    const userEmotion = req.body?.userEmotion?.trim() || null; // legacy self-report
    const imageBuffer = req.file?.buffer || null;

    if (!text || !quickMood) {
      return res.status(400).json({
        error: 'Both text and quick_mood fields are required.',
        disclaimer: DISCLAIMER,
      });
    }

    // Run Milestone 2 local classification pipeline
    let textResult = null;
    let faceResult = null;

    if (text) {
      textResult = await textClassifier.classify(text);
    }
    if (imageBuffer && facialClassifier.isReady()) {
      faceResult = await facialClassifier.classify(imageBuffer);
    }

    // Fuse signals including the self-reported quickMood (emoji)
    const { fuse } = require('../services/fusion');
    const result = fuse(textResult, faceResult, quickMood || userEmotion);

    // Save to Database if employeeId is an integer (valid user_id)
    let dbCheckin = null;
    let recommendation = null;
    
    // Check if it's a valid integer ID
    const userId = parseInt(req.body?.employeeId, 10);
    if (!isNaN(userId)) {
      const { Op } = require('sequelize');
      const startOfDay = new Date();
      startOfDay.setHours(0,0,0,0);
      const endOfDay = new Date();
      endOfDay.setHours(23,59,59,999);
      
      const existingCheckin = await Checkin.findOne({
        where: {
          user_id: userId,
          created_at: {
            [Op.between]: [startOfDay, endOfDay]
          }
        }
      });
      
      if (existingCheckin) {
        return res.status(400).json({
          error: 'You have already completed your daily check-in today. Please come back tomorrow.',
          disclaimer: DISCLAIMER,
        });
      }

      // 1. Save Checkin
      dbCheckin = await Checkin.create({
        user_id: userId,
        text_provided: !!text,
        image_provided: !!imageBuffer,
        raw_text: text || null,
        quick_mood: quickMood
      });

      // 2. Save EmotionResult
      const emotionResult = await EmotionResult.create({
        checkin_id: dbCheckin.id,
        source: 'fusion',
        emotion_label: result.topEmotion,
        confidence_score: result.confidence,
        wellness_score: result.wellnessScore,
        signal_type: result.signalType
      });

      // 3. Generate Recommendation based on fusion result
      recommendation = await generateRecommendation(userId, emotionResult.id, result.topEmotion);

      // 4. Award Points (e.g. 10 points for checkin)
      await awardPoints(userId, 'checkin');
    }

    res.json({
      ...result,
      recommendation: recommendation ? recommendation.suggestion : null,
      buddyAction: recommendation ? recommendation.buddy_action : null
    });
  } catch (err) {
    next(err);
  }
});

// ── GET /api/checkin/progress/:userId ───────────────────────────────────────
router.get('/progress/:userId', requireAuth, async (req, res, next) => {
  try {
    const userId = parseInt(req.params.userId, 10);
    if (isNaN(userId)) return res.status(400).json({ error: 'Invalid userId' });

    const checkins = await Checkin.findAll({
      where: { user_id: userId },
      include: [{ model: EmotionResult }],
      order: [['created_at', 'ASC']]
    });

    res.json(checkins);
  } catch (err) {
    next(err);
  }
});

module.exports = router;
