const { GoogleGenAI } = require('@google/genai');

let ai;
try {
  // Initialize only if key is available
  if (process.env.GEMINI_API_KEY) {
    ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  }
} catch (err) {
  console.log('[Gemini] Not initialized. Fallback mode will be used.');
}

const WELLNESS_CLASSES = ['Happy', 'Calm', 'Stressed', 'Anxious', 'Frustrated', 'Sad'];

/**
 * Analyzes the user check-in using Gemini.
 * Returns { dominantEmotion, wellnessScore, confidence, distribution, disclaimer }
 */
async function analyzeCheckin(text, userEmotion, imageBuffer) {
  if (!ai) {
    return mockAnalyzeCheckin(text, userEmotion);
  }

  try {
    const prompt = `
      You are an expert psychological sentiment analyzer for a wellness app.
      Analyze the following check-in data from a user.
      User explicitly selected emotion emoji: ${userEmotion || 'None'}
      User written text: "${text || 'None'}"
      ${imageBuffer ? 'The user also provided a selfie.' : ''}

      Based on this data, output a JSON object exactly in this format (no markdown tags, just pure JSON):
      {
        "dominantEmotion": "One of: Happy, Calm, Stressed, Anxious, Frustrated, Sad",
        "wellnessScore": <integer from 0 to 100 representing overall wellness, 100 being perfect>,
        "confidence": <float between 0.0 and 1.0 representing your confidence in this analysis>,
        "distribution": {
           "Happy": <float 0-1>,
           "Calm": <float 0-1>,
           "Stressed": <float 0-1>,
           "Anxious": <float 0-1>,
           "Frustrated": <float 0-1>,
           "Sad": <float 0-1>
        }
      }
      The distribution values must sum to 1.0.
    `;

    // Note: We are ignoring the imageBuffer for the API call to keep it fast and simple, 
    // but the prompt is aware if they provided one.
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      }
    });

    const result = JSON.parse(response.text);
    return {
      dominantEmotion: result.dominantEmotion,
      wellnessScore: result.wellnessScore,
      confidence: result.confidence,
      distribution: result.distribution,
      signals: { text: !!text, face: !!imageBuffer, selfReport: !!userEmotion },
      disclaimer: 'This analysis was generated by AI and is not a medical diagnosis.'
    };
  } catch (err) {
    console.error('[Gemini] API error, falling back to mock:', err);
    return mockAnalyzeCheckin(text, userEmotion);
  }
}

/**
 * Chat with the AI Buddy using Gemini.
 */
async function chatBuddy(messages, userEmotion) {
  if (!ai) {
    return mockChatBuddy(messages, userEmotion);
  }

  try {
    const systemPrompt = `You are an AI Buddy for a wellness app called "Mode Mentor".
    The user's recent check-in emotion was: ${userEmotion || 'Unknown'}.
    You are conversational, empathetic, and offer superpowers like suggesting songs, games, hangout plans, or relaxation techniques based on their mood.
    Keep your responses concise, friendly, and formatted nicely. Use emojis.`;

    const chat = ai.chats.create({
      model: 'gemini-2.5-flash',
      config: {
        systemInstruction: systemPrompt
      }
    });

    // Send history
    for (let i = 0; i < messages.length - 1; i++) {
      const msg = messages[i];
      if (msg.role === 'user') {
        await chat.sendMessage({ message: msg.content }); // Just prime the history if needed
      }
    }

    const lastMessage = messages[messages.length - 1].content;
    const response = await chat.sendMessage({ message: lastMessage });
    
    return response.text;
  } catch (err) {
    console.error('[Gemini] Chat API error, falling back to mock:', err);
    return mockChatBuddy(messages, userEmotion);
  }
}

// ── Fallback Mocks (if no API key provided) ──

function mockAnalyzeCheckin(text, userEmotion) {
  console.log('[Gemini] Using advanced local mock for analyzeCheckin.');
  const emotion = userEmotion || 'Calm';
  
  // Simple deterministic hash based on text length and character codes
  let hash = 0;
  if (text) {
    for (let i = 0; i < text.length; i++) {
      hash = ((hash << 5) - hash) + text.charCodeAt(i);
      hash = hash & hash;
    }
  }
  const pseudoRandom = Math.abs(hash) / 2147483647; // 0 to 1

  // Create a realistic looking fake distribution
  const distribution = {};
  WELLNESS_CLASSES.forEach(c => distribution[c] = 0.05);
  distribution[emotion] = 0.75;
  
  const scoreMap = { 'Happy': 90, 'Calm': 80, 'Stressed': 35, 'Anxious': 30, 'Frustrated': 25, 'Sad': 20 };
  let wellnessScore = scoreMap[emotion] || 50;

  // Modulate based on text length using pseudoRandom
  if (text && text.length > 20) {
    wellnessScore += (pseudoRandom * 10 - 5);
  }
  
  // Return realistic dynamic confidence instead of locked 55%
  const confidence = 0.70 + (pseudoRandom * 0.25); // 70% to 95%

  return {
    dominantEmotion: emotion,
    wellnessScore: Math.round(Math.max(0, Math.min(100, wellnessScore))),
    confidence: Math.round(confidence * 100) / 100,
    distribution,
    signals: { text: !!text, face: false, selfReport: !!userEmotion },
    disclaimer: 'This is a simulated AI analysis.'
  };
}

function mockChatBuddy(messages, userEmotion) {
  const lastMsg = messages[messages.length - 1].content.toLowerCase();
  
  if (lastMsg.includes('song') || lastMsg.includes('music')) {
    if (userEmotion === 'Happy') return "Try 'Walking on Sunshine' or upbeat Lo-Fi! 🎶";
    if (userEmotion === 'Sad' || userEmotion === 'Stressed') return "I recommend some calm acoustic guitar or cinematic ambient tracks to relax your mind. 🎧";
    return "How about some chill synthwave to vibe to? 📻";
  }
  if (lastMsg.includes('game') || lastMsg.includes('play')) {
    return "A cozy game like Stardew Valley or Animal Crossing is perfect for winding down. Or if you want action, maybe a quick match in Rocket League? 🎮";
  }
  if (lastMsg.includes('hang') || lastMsg.includes('plan')) {
    return "How about grabbing a coffee with a friend, or going for a walk in a local park? Nature is a great reset! 🌳☕";
  }
  
  return `I hear you! As your simulated AI buddy (since no API key was provided), I suggest taking a 5-minute breather. (Add a Gemini API key in .env for my full superpowers!) 💚`;
}

module.exports = {
  analyzeCheckin,
  chatBuddy
};
